/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab09;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;

public class App {

    public static String[][] downloadStockPrices(String stock, int timeStamp1, int timeStamp2, String interval, String events, boolean includeAdjustedClose){
        //pulls csv stock data from yahoo, returns it as an array of strings
        try {
            //stole this code from the modules, I hope you won't mind ;)
            //my implementation is also exceptionally lazy.
            URL url = new URL("https://query1.finance.yahoo.com/v7/finance/download/" + 
            stock + "?period1=" + timeStamp1 + "&period2=" + timeStamp2 + "&interval=" + interval + "&events=" + events + "&includeAdjustedClose=" + includeAdjustedClose);
            System.out.println(url.toString());
            URLConnection conn = url.openConnection();
            conn.setDoOutput(false);
            conn.setDoInput(true);
            InputStream is = conn.getInputStream();
            InputStreamReader reader = new InputStreamReader(is);
            BufferedReader in = new BufferedReader(reader);
            String line = null;
            ArrayList<String> data = new ArrayList<String>();
            while((line = in.readLine()) != null){
                data.add(line);
            }
            String[][] toReturn = new String[data.size()][data.get(0).length()];
            for (int i = 0; i < data.size(); i++){
                toReturn[i] = data.get(i).split(",");
            }
            return toReturn;
            
        } catch (IOException badUrlException) {
            String[][] toReturn = new String[0][0];
            badUrlException.printStackTrace();
            return toReturn;
        }
    }

    public static void main(String[] args) {
        String stock1 = "GOOG";
        String stock2 = "APPL";
        int timeStamp1 = 1262322000;
        int timeStamp2 = 1451538000;
        String interval = "1mo";
        String events = "history";
        boolean includeAdjustedClose = true;
        downloadStockPrices(stock1, timeStamp1, timeStamp2, interval, events, includeAdjustedClose);

    }
}
