/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab03;

public class SimpleTest {


    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
